version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          cypress-command: 'npm run wait-on && npm run cypress:run'
          start-command: 'npm run start'
