version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          # split specs across machines
          # record results with Cypress Cloud
          cypress-command: 'npx wait-on https://localhost:8080 && npx cypress run --spec "cypress/e2e/spec.cy.js"'
          start-command: 'npm run start'
